# Generated by Django 4.2.1 on 2023-05-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='Password',
            new_name='password',
        ),
    ]
